name: Build macOS

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short
  HUSKY: 0

jobs:
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            arch: arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.95.0'
          targets: ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'v1-rust'
          key: 'rust-shared-stable-${{ matrix.os }}-${{ matrix.target }}'
          workspaces: |
            . -> target
          cache-all-crates: true
          cache-workspace-crates: true

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9
        with:
          run_install: false

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.18.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prebuild
        run: pnpm prebuild ${{ matrix.target }}

      - name: Build Tauri (${{ matrix.target }})
        run: pnpm tauri build --target ${{ matrix.target }}
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Upload .dmg
        uses: actions/upload-artifact@v4
        with:
          name: Clash-Verge-macOS-${{ matrix.arch }}
          path: src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
          if-no-files-found: warn
